os:
  - linux
  - osx

language: c
compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
      - flex
      - bison
      - libgmp-dev
      - libgmp3-dev
      - libpcap0.8-dev
      - libpcap0.8
      - electric-fence
      - gcc-multilib

env:
  global:
    - IPSECVERSION=0.0.0
  matrix:
    - BUILD_ARCH=amd64

# remove the oracle junk, because it otherwise gets updated, and we do not care about it.
before_install:
  - uname -a
  - env | sort -f
  - if [ -z "$TRAVIS_OS_NAME" ]; then TRAVIS_OS_NAME=linux; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install libpcap libgmp flex bison; fi
  - "PATH=$HOME/bin:$PATH export PATH"
  - "echo WERROR=-Werror >Makefile.inc.local"
  - "echo ARCH=${BUILD_ARCH}   >>Makefile.inc.local"
  - if [ "$BUILD_ARCH" = i386 ]; then echo "USERLINKEXTRA=-m32" >>Makefile.inc.local; echo "USERCOMPILEEXTRA=-m32" >>Makefile.inc.local; fi

script:
  - "cat Makefile.inc.local"
  - "make env | sort -f"
  - "make programs ARCH=${BUILD_ARCH}"
  - "make check ARCH=${BUILD_ARCH}"
